# Generated by Django 4.2.13 on 2024-06-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(default='https://cdn.shopify.com/s/files/1/0041/3600/9841/files/coming_soon_large.jpg?v=1540936113', max_length=500),
        ),
    ]
